example:
  property: I AM THE DEFAULT
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database: POSTGRESQL
    show-sql: true

  sql:
    init:
      platform: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

server:
  port: 8080

