example:
  property: I AM DEV

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

appl:
  name: ALOHA

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
