example:
  property: I AM PROD

# DataSource settings: set here your own configurations for the database 
spring:
  datasource:
    url: jdbc:postgresql://database:5432/ostock_prod
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '{cipher}a5e09672aa357bc6e98c69a3d9781bcfd563e042e1ce7c33503d272b83814847'